### ISSUE TITLE
Does the project work on android devices

### ISSUE THREAD

**Issue by wangzf88** [AkanshDivker/Simple-ECS#3]
Hello, Akansh Divker
     Does the project work on android devices?
     thank you! happy every day :-)

**Comment by AkanshDivker** [comment]
Hi,

There is nothing platform-specific being used in this project. I haven't tested it on Android, but it should work. The only thing that might need adjusting is the input system. A mobile device probably won't be able to simulate as many entities, but other than that and the input, there should be no issues 😃

**Comment by wangzf88** [comment]
Thank you for your answer, but it crashed when it ran on my Android VR devices, I thought maybe there was something wrong with me.

**Comment by AkanshDivker** [comment]
Seems like VR isn't supported yet for Hybrid Renderer. Once it's supported, I imagine it should work as intended on VR devices without any extra work required @wangzf88 

https://forum.unity.com/threads/dots-for-vr.1049432/#post-6788336

**Comment by wangzf88** [comment]
Thank you very much for your response，I read the post carefully，I found The Poster already make hybrid rendered on a Quest 2, But I use a different brand VR device. It must be use IL2CPP. I guess with my little knowledge, whether IL2CPP and Burst of DOTS are in conflict?
